### ISSUE TITLE
Kafka Library Follow Up

### ISSUE THREAD

**Issue by ray-kast** [holaplex/hub-core#5]
## Remaining Items
- [ ] Helper macros for `prost`/`rdkafka` glue code
- [x] Figure out schema management workflow
- [x] Deployment of Redpanda schema registry
- [x] Review `hub-core` API after finishing `hub-orgs` setup
- [x] **BONUS:** Finish documenting `hub-core` and figure out system dev-dependencies

**Comment by kespinola** [comment]
schema management workflow

https://github.com/holaplex/hub-schema-registry/issues/1
